# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6468676190c825f5b77afaaeac2e420a6d1efa3cd7e35c24385ab59ef8a59a3c4d72a57d9b7d0484fa11cf29654fb58231ae1fbb7a9a924154502bc58eaebfe2

test:
  secret_key_base: a995350efd63f680000ddc8991f4775fdabf0a50e8d4bb5a964662d61891c38fa977d2d11dcde0cc1ce711ae64c8d33740438734e3488f6fe2f9b47126037be9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
